#!/bin/bash
# Run this from within the qemu git directory.

TESTCASE=testcase

prepare() {
  # copy disk etc
} 

compile() {
  make distclean
  git clean -f
  make clean
  ./configure --target-list="x86_64-softmmu" --disable-werror --enable-kvm --disable-docs --enable-debug
  make -j`nproc` || exit 125
}

prepare
compile

echo "Testing..."
sudo $(dirname $0)/${TESTCASE} 2>&1 | tee testcase.log

# Check value
retval=125
if grep -i 'RESULT: FAIL' testcase.log ; then
    retval=0
fi

if grep -i 'RESULT: PASS' testcase.log ; then
    retval=1
fi

exit $retval

